export type Choice = {
  id: string
  vi: string
  en?: string
  note?: string
  freetext?: boolean
}

export type Group = {
  id: string
  vi: string
  en: string
  hint?: string
  toggle?: { vi: string; en: string }
  columns?: 1 | 2
  choices: Choice[]
}

export const patientFields = [
  { id: "name", vi: "Tên bệnh nhân", en: "Patient's name", span: 2 },
  { id: "dob", vi: "Ngày sinh", en: "DOB", span: 1 },
  { id: "address", vi: "Địa chỉ bệnh nhân", en: "Address", span: 3 },
  { id: "phone", vi: "Điện thoại", en: "Telephone", span: 1 },
  { id: "id", vi: "ID", en: "ID", span: 1 },
]

export const groups: Group[] = [
  {
    id: "endoscopy",
    vi: "Nội soi",
    en: "Endoscopy",
    hint: "Lưu ý: Không ăn uống trước khi nội soi tiêu hóa.",
    columns: 2,
    choices: [
      { id: "ent", vi: "Tai mũi họng" },
      { id: "stomach-sed", vi: "Dạ dày an thần" },
      { id: "ear", vi: "Tai" },
      { id: "colon-sed", vi: "Đại trực tràng an thần" },
      { id: "nose", vi: "Mũi" },
      { id: "colon", vi: "Trực tràng an thần" },
      { id: "larynx", vi: "Họng, Thanh quản" },
    ],
  },
  {
    id: "functional",
    vi: "Thăm dò CN",
    en: "Functional test",
    columns: 2,
    choices: [
      { id: "ecg", vi: "Điện tâm đồ" },
      { id: "eeg", vi: "Điện não đồ" },
      { id: "emg2a", vi: "Điện cơ 2 tay" },
      { id: "emg2l", vi: "Điện cơ 2 chân" },
      { id: "spiro", vi: "Đo hô hấp ký" },
      { id: "bone-us", vi: "Đo loãng xương siêu âm" },
    ],
  },
  {
    id: "xray",
    vi: "X-Quang",
    en: "X-Ray",
    columns: 1,
    choices: [
      { id: "chest", vi: "Ngực" },
      { id: "heart-lung", vi: "Tim phổi" },
      { id: "spine", vi: "Cột sống" },
      { id: "abdomen", vi: "Bụng" },
      { id: "stomach", vi: "Dạ dày" },
      { id: "skull", vi: "Sọ" },
      { id: "sinus", vi: "Xoang" },
      { id: "bone", vi: "Xương" },
      { id: "joint", vi: "Khớp" },
      { id: "pelvis", vi: "Khung chậu" },
      { id: "xother", vi: "Khác", freetext: true },
    ],
  },
  {
    id: "ultrasound",
    vi: "Siêu âm",
    en: "Ultrasound",
    columns: 2,
    choices: [
      { id: "abd-total", vi: "Bụng TQ" },
      { id: "thyroid2", vi: "Thai" },
      { id: "neck", vi: "Giáp" },
      { id: "heart-us", vi: "Tim" },
      { id: "soft", vi: "Mô mềm" },
      { id: "vessel-up", vi: "Mạch máu chi trên" },
      { id: "gyn", vi: "Phụ khoa" },
      { id: "vessel-low", vi: "Mạch máu chi dưới" },
      { id: "breast", vi: "Vú" },
      { id: "carotid", vi: "Mạch cảnh" },
      { id: "us-other", vi: "Khác", freetext: true },
      { id: "renal-vessel", vi: "Mạch máu Thận" },
    ],
  },
  {
    id: "msct",
    vi: "MSCT",
    en: "",
    toggle: { vi: "Có cản quang", en: "Contrast" },
    columns: 2,
    choices: [
      { id: "brain", vi: "Não" },
      { id: "pulm-vessel", vi: "Mạch máu phổi" },
      { id: "sinus2", vi: "Xoang" },
      { id: "renal-vessel2", vi: "Mạch máu thận" },
      { id: "orbit", vi: "Hốc mắt" },
      { id: "mesenteric", vi: "Mạch máu mạc treo" },
      { id: "ear2", vi: "Tai" },
      { id: "low-vessel", vi: "Mạch máu chi dưới" },
      { id: "neck2", vi: "Vùng cổ" },
      { id: "up-vessel", vi: "Mạch máu chi trên" },
      { id: "chest2", vi: "Ngực" },
      { id: "coronary", vi: "Động mạch vành" },
      { id: "abd2", vi: "Bụng" },
      { id: "carotid2", vi: "Động mạch cảnh" },
      { id: "pelvis2", vi: "Phổi liều thấp" },
      { id: "abd-aorta", vi: "Động mạch chủ bụng" },
      { id: "pelvis3", vi: "Chậu" },
      { id: "chest-aorta", vi: "Động mạch chủ ngực" },
      { id: "urinary", vi: "Hệ niệu" },
      { id: "bronch", vi: "Động mạch phế quản" },
      { id: "spine2", vi: "Cột sống" },
      { id: "cerebral-a", vi: "Động mạch não" },
      { id: "limb-up", vi: "Chi trên" },
      { id: "ct-renal", vi: "CT toàn thân" },
      { id: "limb-low", vi: "Chi dưới" },
      { id: "msct-other", vi: "Khác", freetext: true },
    ],
  },
  {
    id: "mri",
    vi: "MRI",
    en: "",
    toggle: { vi: "Có cản từ", en: "Contrast" },
    columns: 2,
    choices: [
      { id: "brain-mri", vi: "Sọ não" },
      { id: "limb-up-mri", vi: "Chi trên" },
      { id: "neck-mri", vi: "Vùng cổ" },
      { id: "limb-low-mri", vi: "Chi dưới" },
      { id: "orbit-mri", vi: "Hốc mắt" },
      { id: "abd-mri", vi: "Bụng" },
      { id: "chest-mri", vi: "Lồng ngực" },
      { id: "pelvis-mri", vi: "Chậu" },
      { id: "breast-mri", vi: "Tuyến vú" },
      { id: "brain-vessel-mri", vi: "Mạch máu não" },
      { id: "abd-mri2", vi: "Bụng" },
      { id: "aorta-mri", vi: "Động mạch chủ" },
      { id: "pelvis-mri2", vi: "Chậu" },
      { id: "up-vessel-mri", vi: "Mạch máu chi trên" },
      { id: "face-mri", vi: "Vùng Mặt - Cổ / Đáy sọ" },
      { id: "low-vessel-mri", vi: "Mạch máu chi trên" },
      { id: "spine-mri", vi: "Cột sống" },
      { id: "perfusion-mri", vi: "Tưới máu" },
      { id: "joint-mri", vi: "Khớp (Vai / Gối / Háng)" },
      { id: "whole-mri", vi: "MRI Toàn thân" },
      { id: "mri-desc", vi: "Mô tả khác", freetext: true },
    ],
  },
]

export const packages: Group[] = [
  {
    id: "health",
    vi: "Gói sức khỏe",
    en: "Package",
    columns: 1,
    choices: [
      { id: "child", vi: "Gói tổng quát trẻ em" },
      { id: "basic-m", vi: "Gói tổng quát cơ bản (Nam)" },
      { id: "basic-f-s", vi: "Gói tổng quát cơ bản (Nữ - Độc thân)" },
      { id: "basic-f-m", vi: "Gói tổng quát cơ bản (Nữ - GĐ)" },
      { id: "vip-m", vi: "Gói tầm soát tổng quát VIP (Nam)" },
      { id: "vip-f-s", vi: "Gói tầm soát tổng quát VIP (Nữ - Độc thân)" },
      { id: "vip-f-m", vi: "Gói tầm soát tổng quát VIP (Nữ - GĐ)" },
      { id: "cervical", vi: "Tầm soát ung thư vú và cổ tử cung" },
      { id: "stroke", vi: "Tầm soát đột quỵ" },
      { id: "cardio", vi: "Tầm soát tim mạch" },
      { id: "cancer-m", vi: "Tầm soát dấu ấn ung thư (Nam)" },
      { id: "cancer-f", vi: "Tầm soát dấu ấn ung thư (Nữ)" },
      { id: "marriage-m", vi: "Gói tiền hôn nhân (Nam)" },
      { id: "marriage-f", vi: "Gói tiền hôn nhân (Nữ)" },
    ],
  },
  {
    id: "maternity",
    vi: "Gói sinh",
    en: "Maternity Packages",
    columns: 1,
    choices: [
      { id: "normal", vi: "Gói sinh thường cơ bản" },
      { id: "csection", vi: "Gói sinh mổ cơ bản" },
      { id: "normal-full", vi: "Gói sinh thường trọn gói (tuần thai 14 - 40)" },
      { id: "csection-full", vi: "Gói sinh mổ trọn gói (tuần thai 14 - 40)" },
    ],
  },
]

// Helper: build IgM / IgG pair choices from a base label
const igPair = (id: string, label: string): Choice[] => [
  { id: `${id}-igm`, vi: `${label} IgM` },
  { id: `${id}-igg`, vi: `${label} IgG` },
]

export const labGroups: Group[] = [
  {
    id: "urine",
    vi: "Nước tiểu",
    en: "Urine",
    columns: 1,
    choices: [
      { id: "u-total", vi: "Tổng phân tích nước tiểu" },
      { id: "u-microalb", vi: "Micro Albumin" },
      { id: "u-protein24", vi: "Đạm niệu 24 giờ" },
      { id: "u-ion", vi: "Ion đồ niệu" },
      { id: "u-creat", vi: "Creatinine" },
      { id: "u-amylase", vi: "Amylase" },
      { id: "u-cortisol", vi: "Cortisol tự do / NT 24 giờ" },
      { id: "u-addis", vi: "Cặn Addis" },
      { id: "u-sediment", vi: "Soi cặn lắng" },
      { id: "u-hcg", vi: "HCG định tính" },
      { id: "u-drug", vi: "EXN ma túy 4 trong 1 (MOD-AMP-MET - THC)" },
    ],
  },
  {
    id: "hematology",
    vi: "Huyết học",
    en: "Hematology",
    columns: 1,
    choices: [
      { id: "h-cbc", vi: "DTPT tế bào máu (laser)" },
      { id: "h-esr", vi: "Tốc độ máu lắng" },
      { id: "h-abo", vi: "Nhóm máu ABO (RH)" },
      { id: "h-retic", vi: "Hồng cầu lưới" },
      { id: "h-plt", vi: "Độ tập trung tiểu cầu" },
      { id: "h-smear", vi: "Phết máu ngoại biên" },
      { id: "h-malaria", vi: "KST sốt rét" },
      { id: "h-malaria-ag", vi: "Malaria Ag" },
      { id: "h-electro", vi: "Điện di huyết sắc tố" },
      { id: "h-g6pd", vi: "G6PD" },
      { id: "h-hargraves", vi: "TB Hargraves (LE.Cell)" },
    ],
  },
  {
    id: "coagulation",
    vi: "Đông máu",
    en: "Coagulation",
    columns: 1,
    choices: [
      { id: "c-clot", vi: "Máu đông" },
      { id: "c-aptt", vi: "APTT (TCK)" },
      { id: "c-fibrinogen", vi: "Định lượng Fibrinogen" },
      { id: "c-ddimer", vi: "D Dimer" },
      { id: "c-proteinc", vi: "Protein C" },
      { id: "c-proteins", vi: "Protein S" },
      { id: "c-quick", vi: "Thời gian QUICK (Prothrombin time, IRN)" },
    ],
  },
  {
    id: "fluid",
    vi: "Dịch",
    en: "Fluid analysis",
    columns: 1,
    choices: [
      { id: "f-cyto", vi: "Sinh hóa, tế bào" },
      { id: "f-ph", vi: "pH" },
      { id: "f-amylase", vi: "Amylase" },
      { id: "f-bili", vi: "Bilirubin" },
      { id: "f-ldh", vi: "LDH" },
      { id: "f-liquidprep", vi: "Liquid Prep" },
      { id: "f-fresh", vi: "Soi tươi (mẫu da, dịch…)" },
      { id: "f-stain", vi: "Soi + Nhuộm tiêu bản" },
      { id: "f-pap", vi: "Pap' smear" },
    ],
  },
  {
    id: "molecular",
    vi: "SHPT",
    en: "Molecular bio.",
    columns: 1,
    choices: [
      { id: "m-hbvdna", vi: "HBV-DNA" },
      { id: "m-hcvrna", vi: "HCV (RT-RNA)" },
      { id: "m-hcvgeno", vi: "HCV GENOTYPE" },
      { id: "m-cmvpcr", vi: "CMV PCR" },
      { id: "m-denguepcr", vi: "Dengue Virus PCR" },
      { id: "m-chlamydiapcr", vi: "Chlamydia PCR" },
      { id: "m-hpvpcr", vi: "HPV PCR" },
      { id: "m-h1n1", vi: "Virus H1N1 PCR" },
      { id: "m-h5n1", vi: "Virus H5N1 PCR" },
      { id: "m-laodich", vi: "PCR LAO (dịch)" },
      { id: "m-laodam", vi: "PCR LAO (đàm)" },
    ],
  },
  {
    id: "biochem",
    vi: "Sinh hóa - Miễn dịch",
    en: "Biochemistry - Immunology",
    columns: 2,
    choices: [
      { id: "b-urea", vi: "Urea" },
      { id: "b-creat", vi: "Creatinine" },
      { id: "b-gfr", vi: "Độ lọc cầu thận" },
      { id: "b-glucose", vi: "Glucose" },
      { id: "b-hba1c", vi: "HbA1C" },
      { id: "b-ogtt2", vi: "NP dung nạp đường (2h)" },
      { id: "b-ogtt3", vi: "NP dung nạp đường thai kỳ (3h)" },
      { id: "b-chol", vi: "Cholesterol" },
      { id: "b-trig", vi: "Triglycerid" },
      { id: "b-hdl", vi: "HDL-C" },
      { id: "b-ldl", vi: "LDL-C" },
      { id: "b-vldl", vi: "VLDL-C" },
      { id: "b-lipid", vi: "Lipid" },
      { id: "b-cpk", vi: "CPK" },
      { id: "b-ldh", vi: "LDH" },
      { id: "b-ckmb", vi: "CK-MB" },
      { id: "b-troponin", vi: "Troponin I" },
      { id: "b-prog", vi: "Progesterone" },
      { id: "b-ntprobnp", vi: "NT-PRO BNP" },
      { id: "b-bili-total", vi: "Bilirubin toàn phần" },
      { id: "b-bili-direct", vi: "Bilirubin trực tiếp" },
      { id: "b-bili-indirect", vi: "Bilirubin gián tiếp" },
      { id: "b-alt", vi: "ALT (SGPT)" },
      { id: "b-ast", vi: "AST (SGOT)" },
      { id: "b-ggt", vi: "GGT" },
      { id: "b-protein-total", vi: "Protein toàn phần" },
      { id: "b-albumin", vi: "Albumin" },
      { id: "b-ag", vi: "A/G" },
      { id: "b-amylase", vi: "Amylase" },
      { id: "b-lipase", vi: "Lipase" },
      { id: "b-alp", vi: "Alkalin phosphatase" },
      { id: "b-acp", vi: "Acid phosphatase" },
      { id: "b-eprotein", vi: "Điện di protein" },
      { id: "b-eimmuno", vi: "Điện di miễn dịch" },
      { id: "b-uric", vi: "Uric Acid" },
      { id: "b-crp", vi: "CRP" },
      { id: "b-aslo", vi: "ASLO" },
      { id: "b-rf", vi: "RF" },
      { id: "b-pct", vi: "Procalcitonin (PCT)" },
      { id: "b-ion", vi: "Ion đồ (Na, K, Ca ion hóa, Cl)" },
      { id: "b-mg", vi: "Mg++" },
      { id: "b-fe", vi: "Fe" },
      { id: "b-zn", vi: "Kẽm" },
      { id: "b-ferritin", vi: "Ferritin" },
      { id: "b-scc", vi: "SCC" },
      { id: "b-anticcp", vi: "Anti CCP" },
      { id: "b-cystracine", vi: "Cystracine C" },
      { id: "b-prolactine", vi: "Prolactine" },
      { id: "b-dengue-igg-igm", vi: "Dengue IgG/IgM (Test nhanh)" },
      { id: "b-betahcg", vi: "Định lượng Beta HCG / máu" },
      { id: "b-tsh", vi: "TSH" },
      { id: "b-t3", vi: "T3" },
      { id: "b-t4", vi: "T4" },
      { id: "b-ft3", vi: "Free T3" },
      { id: "b-ft4", vi: "Free T4" },
      { id: "b-trab", vi: "TSH Receptor (TRAb)" },
      { id: "b-tpoab", vi: "TPO Ab" },
      { id: "b-tgag", vi: "Thyroglobulin Ag" },
      { id: "b-tgab", vi: "Thyroglobulin Ab" },
      { id: "b-thyrocalci", vi: "Thyrocalcitonin" },
      { id: "b-pth", vi: "PTH" },
      { id: "b-cortisol", vi: "Cortisol / máu" },
      { id: "b-ebv-igg", vi: "EBV IgG" },
      { id: "b-igm", vi: "IgM" },
      { id: "b-toxo", vi: "Toxo gondi" },
      { id: "b-acth", vi: "ACTH / máu" },
      { id: "b-catechol", vi: "Catecholamin / Máu" },
      { id: "b-aldosterone", vi: "Aldosterone" },
      { id: "b-testosterone", vi: "Testosterone" },
      { id: "b-estradiol", vi: "Estradiol (E2)" },
      { id: "b-progesterone2", vi: "Progesterone" },
      { id: "b-lh", vi: "LH" },
      { id: "b-gh", vi: "GH" },
      { id: "b-adh", vi: "ADH" },
      { id: "b-fsh", vi: "FSH" },
      { id: "b-ca199", vi: "CA 19-9" },
      { id: "b-ca125", vi: "CA 125" },
      { id: "b-ca153", vi: "CA 15-3" },
      { id: "b-ca724", vi: "CA 72-4" },
      { id: "b-totalpsa", vi: "Total PSA" },
      { id: "b-freepsa", vi: "Free PSA" },
      { id: "b-afp", vi: "AFP" },
      { id: "b-nse", vi: "NSE" },
      { id: "b-cyfra", vi: "Cyfra 21.1" },
      { id: "b-folate", vi: "Folate" },
      { id: "b-acetamino", vi: "Acetaminophene / máu" },
      { id: "b-antitp", vi: "Anti TP" },
      { id: "b-ige", vi: "IgE" },
      { id: "b-rida", vi: "RIDA ALLERGY SCREEN" },
      { id: "b-cpeptid", vi: "C-Peptid" },
      { id: "b-insuline", vi: "Insuline" },
      { id: "b-pep1", vi: "Peprinogen 1" },
      { id: "b-pep2", vi: "Peprinogen 2" },
      { id: "b-pivka", vi: "Pivka II" },
      { id: "b-hbsag", vi: "HBsAg" },
      { id: "b-antihbs", vi: "Anti HBs" },
      { id: "b-hbeag", vi: "HBeAg-Miễn dịch tự động" },
      { id: "b-hbeab", vi: "HBeAb-Miễn dịch tự động" },
      { id: "b-hbc-igg", vi: "HBc IgG" },
      { id: "b-hbc-igm", vi: "HBc IgM" },
      { id: "b-hcv-ab", vi: "HCV Ab" },
      { id: "b-hcv-ag", vi: "HCV Ag" },
      { id: "b-hiv", vi: "HIV Ag/Ab" },
      { id: "b-b12", vi: "Vitamin B12" },
      ...igPair("b-hav", "HAV"),
      ...igPair("b-hev", "HEV"),
      ...igPair("b-quaibi", "Quai bị"),
      ...igPair("b-soi", "Sởi"),
      ...igPair("b-thuydau", "Thủy đậu"),
      ...igPair("b-cmv", "CMV"),
      ...igPair("b-ebv-viral", "EBV"),
      ...igPair("b-rubella", "Rubella"),
      ...igPair("b-herpes", "Herpes Simplex"),
      ...igPair("b-vnnb", "Viêm não NB"),
      ...igPair("b-legionella", "Leigionella pneu"),
      ...igPair("b-chlamydia-pneu", "Chalamydia pneu"),
      ...igPair("b-mycoplasma", "Mycoplasma pneu"),
    ],
  },
  {
    id: "elisa",
    vi: "KT ELISA",
    en: "",
    columns: 2,
    choices: [
      ...igPair("e-candida", "Candida"),
      ...igPair("e-aspergilus", "Aspergilus"),
      ...igPair("e-salmonella", "Salmonella"),
      ...igPair("e-dengue", "Dengue"),
      ...igPair("e-hpylori", "H.Pylori"),
      { id: "e-ns1ag", vi: "NS1Ag" },
      { id: "e-leptospira", vi: "Leptospira IgG" },
      { id: "e-amibe", vi: "Amibe" },
      { id: "e-angiostrongylus", vi: "Angiostrongylus" },
      { id: "e-cysticercus", vi: "Cysticercus" },
      { id: "e-fasciola", vi: "Fasciola hepatica" },
      { id: "e-gnathostoma", vi: "Gnathostoma" },
      { id: "e-toxogondii", vi: "Toxo gondii" },
      { id: "e-paragonimus", vi: "Paragonimus" },
      { id: "e-strongyloides", vi: "Strongyloides" },
      { id: "e-schistoma", vi: "Schistoma" },
      { id: "e-toxocara", vi: "Toxocara canis" },
      { id: "e-trichinella", vi: "Trichinella" },
      { id: "e-echinococcus", vi: "Echinococcus" },
      { id: "e-ascaris", vi: "Ascaris lumbricoides" },
      { id: "e-ana", vi: "ANA" },
    ],
  },
  {
    id: "microbiology",
    vi: "Vi sinh",
    en: "Microbiology",
    columns: 1,
    choices: [
      { id: "vs-bk", vi: "BK (Đàm)" },
      { id: "vs-dam", vi: "Cấy đàm + KSĐ" },
      { id: "vs-mu", vi: "Cấy mủ + KSĐ" },
      { id: "vs-phan", vi: "Cấy phân + KSĐ" },
      { id: "vs-hpylori", vi: "Cấy H.PYLORI" },
      { id: "vs-hpc13", vi: "HP test hơi thở (C13)" },
      { id: "vs-nam", vi: "Cấy nấm" },
      { id: "vs-mau", vi: "Cấy máu + KSĐ" },
      { id: "vs-nuoctieu", vi: "Cấy nước tiểu + KSĐ" },
    ],
  },
  {
    id: "stool",
    vi: "Phân",
    en: "Stool",
    columns: 1,
    choices: [
      { id: "s-kst", vi: "Soi tìm KST đường ruột" },
      { id: "s-occult", vi: "Máu ẩn" },
    ],
  },
]
